"""Agregar columna localidad a Usuario

Revision ID: 5e241139ed15
Revises: 90e01555395a
Create Date: 2023-11-28 17:41:29.643348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e241139ed15'
down_revision = '90e01555395a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localidad', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('localidad')

    # ### end Alembic commands ###
