"""Agregar campo localidad a Usuario

Revision ID: 90e01555395a
Revises: 
Create Date: 2023-11-28 17:27:35.202234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90e01555395a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('usuarios')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['dni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('usuarios',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('apellido', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('dni', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('direccion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('numero', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('localidad', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('codigo_postal', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('telefono', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('confirmar_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('contrasena', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('confirmar_contrasena', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('consulta', mysql.TEXT(), nullable=True),
    sa.CheckConstraint('(`contrasena` = `confirmar_contrasena`)', name='usuarios_chk_1'),
    sa.CheckConstraint('(`email` = `confirmar_email`)', name='usuarios_chk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
